//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int user_id { get; set; }
        public int game_id { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
        public Nullable<int> like { get; set; }
        public Nullable<int> dislike { get; set; }
    
        public virtual User User { get; set; }
        public virtual Game Game { get; set; }
    }
}
